### ISSUE TITLE
When is Beta coming out? Need help?

### ISSUE THREAD

**Issue by DanielCauser** [crossql/crossql#8]

**Comment by ChaseFlorell** [comment]
At this point I think we need to be "Alpha".
What needs to be done right now is to add the nuget meta data and fully update the build scripts to support this new format. Then I need to spin up an App Veyor instance to make sure the builds are passing.

Essentially I need to re-write the CI.

**Comment by DanielCauser** [comment]
Nice, I can help with the nuget meta data!

**Comment by ChaseFlorell** [comment]
Pre-Releases are now available here
https://ci.appveyor.com/nuget/crossql
